### ISSUE TITLE
Refine non profit definition

### ISSUE THREAD

**Issue by pierreozoux** [gandhiano/technology-degrowth#2]
`that prohibits any commercial usage of it. It's success was so immense that most of the world wide web, as well as a huge number consumer devices - from Android smartphones, to TomTom GPS - are built on top of the Linux Kernel.`

It is strange that it prohibits commercial usage and is used by TomTom which is not F/LOSS :)

**Comment by gandhiano** [comment]
Refined the licensing aspects, closed with d570b4d854bd7851cde7bdf6ee0258dec2ed62f6
