### ISSUE TITLE
Refine the "we"

### ISSUE THREAD

**Issue by gandhiano** [gandhiano/technology-degrowth#3]
I miss a clear definition of the "we" for the text. I have for now written "free software movement", because it's concrete and addresses most of which is written here. On the other hand, I am afraid it is too focused on the software and missing some of the ideas of stacktivism, getting control and shaping the digital infrastructure where we run as a whole.

Would like to hear opinions here.

@pierreozoux @almereyda

**Comment by pierreozoux** [comment]
I feel part of the free software movement.
It is just that we live in the cloud era, and we need some people to host these free software! That's it ;)

Some people are also paid to install free software, or paid to provide support, and as them, we are part of the nebula around free software that is offering service.

**Comment by gandhiano** [comment]
That's a good clarification, and it's also what I feel. I will take it and include in the next changes.
