### ISSUE TITLE
Shortly distinguish free vs open source software

### ISSUE THREAD

**Issue by gandhiano** [gandhiano/technology-degrowth#4]
There are obviously [differences](https://en.wikipedia.org/wiki/Free_software_movement#Open_source), which should be made clear.

Also related to #3, where it might be interesting to consider if we talk about free software movement, or rather FOSS/FLOSS.

**Comment by pierreozoux** [comment]
I like the term FLOSS, and I think, the first time you use it, you can give a quick definition linked to the article you mentioned.

**Comment by gandhiano** [comment]
Reopening, as I find this the position/approach of the liberal (and pro-guns) ESR and the OSI in regard to free software (negative/pejoratively seen by business, therefore open source as "better" language to communicate with the establishment) as a relevant aspect of the narrative. ESR and colleagues saw it as a problem not only because of the ambiguity of the meaning of "free", but also because of how it was seen by the establishment.

>  It seemed clear to us in retrospect that the term `free software' had done our movement tremendous damage over the years. Part of this stemmed from the fact that the word`free' has two different meanings in the English language, one suggesting a price of zero and one related to the idea of liberty. Richard Stallman, whose Free Software Foundation has long championed the term, says `Think free speech, not free beer'' but the ambiguity of the term has nevertheless created serious problems -- especially since most`free software'' is also distributed free of charge.
> 
> Most of the damage, though, came from something worse -- the strong association of the term `free software' with hostility to intellectual property rights, communism, and other ideas hardly likely to endear it to an MIS manager.
> 
> In conventional marketing terms, our job was to rebrand the product, and build its reputation into one the corporate world would hasten to buy.

From ["The Revenge of the Hackers"](http://catb.org/~esr/faqs/hacker-revenge.html)

**Comment by pierreozoux** [comment]
What are:
- ESR
- OSI
- MIS

**Comment by gandhiano** [comment]
- ESR = [Eric S. Raymond](https://en.wikipedia.org/wiki/Eric_S._Raymond)
- OSI = [Open Source Initiative](https://opensource.org/)
- MIS = [management information systems](https://en.wikipedia.org/wiki/Management_information_system)

**Comment by gandhiano** [comment]
I'm closing this again, as there is no space to develop this argument further, due to character limitations of the book chapter (#10). It might be interesting to further explore this in future developments of the document though.
