### ISSUE TITLE
Describe history and philosophy of the web

### ISSUE THREAD

**Issue by gandhiano** [gandhiano/technology-degrowth#5]
The web plays a central role in the critique and argument made along the chapter. There should be 1-2 paragraphs in question 1 2 describing the emergence of the web and its' key ideas (q1), as well as its' protagonists (Tim Berners-Lee, W3C, etc.).

Other ideas:
- reference to the essentially open source stack of the web
- institutional development of the web (e.g. "commercialization" after 96, corporate platforms and clouds)

**Comment by almereyda** [comment]
Well, it was not only timbl who brought up everything. There was all the work of Xerox Parc and others leading to Hypertext systems. Hypercard was one of such predecessors.

Also is "Philosophy of the Web" a reknown scientific discipline, which doesn't need to bring the "world wide" prefix.

**Comment by gandhiano** [comment]
Would you like to contribute a paragraph on this @almereyda ? I'm sure you can better write something out of the head than me :)

**Comment by gandhiano** [comment]
This has been addressed in some of the latest commits. The text needs to be polished, but the topic is there. It would be out of scope (and space) to describe the whole history of the hypertext.
